### PR TITLE
docs: add note using CRA

### PR DESCRIPTION
**Pull request by marcosvega91**
Regarding the issue https://github.com/mswjs/msw/issues/354
I have added a note in the setup

image

### CODE REVIEW

**Comment by kettanaito** [comment]
Hey, @marcosvega91. Thanks for adding this note, it's a good point to have.

However, since our tutorial is aimed at both browser and Node integration, I'd rather add this note to Integrate > Browser at the end of the [Setup](https://mswjs.io/docs/getting-started/integrate/browser#setup) section. That way we are suggesting this action to those developers who are going to use MSW in a browser. If you are using MSW in Node, you don't have to remove any lines, and suggesting that may be confusing.

Since in the integration step a reader may lose the context of being in CRA, I think we need to add a note that this step is necessary only if you are using CRA.

**Comment by marcosvega91** [comment]
You're right, I'll move in the other section 👍

**Comment by marcosvega91** [comment]
I have updated the repo, I have added a new section at the end of `browser.mdx`

image

**Review by kettanaito — APPROVED** [review]
Thank you for these changes, @marcosvega91!

**Pull request merged**
