### PR TITLE
Docs (Request): Removes deprecated "query", fixes "URL" type, adds "keepalive"

### PR DESCRIPTION
**Pull request by thomasmery**
@kettanaito 

I noticed the _query_ ppty was absent from the ts types.

I found a thread where you say it's been deprecated but found it in the docs

don't know if this is valid and if so if you want to phrase it like that (or no at all ;)

thanks

### CODE REVIEW

**Comment by kettanaito** [comment]
Hey, @thomasmery! That's a good point. I'd remove the `query` mention from the [Request properties](https://mswjs.io/docs/api/request#properties), but I don't think we need any kind of deprecation warning at this point. Could you please adjust your changes, so we could merge them? Thanks.

**Comment by thomasmery** [comment]
Hi @kettanaito 

I can do that sure,

also `url` is typed as _string_ on this page

I'll change it for _URL_ as in the typings

seems like the _keepalive_ ppty is missing but I could not find it on _Request_ but in _RequestInit_ (but maybe I'm confused)

| `keepalive`      | [`RequestInit.keepalive`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Keep-Alive)         |

?

**Comment by kettanaito** [comment]
> also url is typed as string on this page

Thank you for spotting and changing that! `req.url` is indeed an instance of the `URL` class.

> seems like the keepalive ppty is missing but I could not find it on Request but in RequestInit (but maybe I'm confused)

I believe you've confused it with a similar header name. `req.keepalive` is a `boolean` property that indicates whether this request can outlive the context it's been created in (per official type declaration). If you would like to add that property, please go ahead! You can use the official description:

```
Returns a boolean indicating whether or not request can outlive the global in which it was created.
```

**Comment by thomasmery** [comment]
Hi,

ah sorry lacked time
thanks!!

**Comment by kettanaito** [comment]
Hey, absolutely no worries :) Your contribution is much appreciated.

**Pull request merged**
