### PR TITLE
docs(limitations): remove "Parallel runs"

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
We now have `boundary()`

https://mswjs.io/docs/api/setup-server/boundary

### CODE REVIEW

**Review by kettanaito — APPROVED** [review]
Didn't realized we have a limitation to remove! Thank you, @MichaelDeBoey! 👏

**Comment by MichaelDeBoey** [comment]
@kettanaito Only one left now! ☺️

**Comment by kettanaito** [comment]
Alas, not much we can/should do about Firefox! Still something the developers should be aware of.

**Review by Raafey-Khan — COMMENTED** [review]
Great changes

**Pull request merged**
